### ISSUE TITLE
Missing ESP8266WiFi.h on compiling the example?

### ISSUE THREAD

**Issue by bubba198** [myDevicesIoT/Cayenne-MQTT-ESP8266#18]
In file included from Cayenne_example_ESP8266_5-30-2020.ino:6:0:
C:\Users\boyan.biandov\Documents\Arduino\libraries\Cayenne-MQTT-ESP-master\src/CayenneMQTTESP8266.h:21:25: fatal error: ESP8266WiFi.h: No such file or directory
 #include <ESP8266WiFi.h>
                         ^
compilation terminated.
Error compiling.

I am using the latest 8266 board and I have many sketches working and NONE requires the import of ESP8266WiFi.h but for some reason the CayenneMQTTESP8266 does?

For what reason? I've never had to do that and my 8266 sketches work just fine?

As a result I can not use the CayenneMQTTESP8266 library for the Cayenne example sketh?

Any input will be apprciated!

Thank you

**Comment by jburhenn** [comment]
We include the ESP8266WiFi.h to in order to use the WiFi connection to send data. I'm not sure what the other sketches might be using for WiFi connections or if they perhaps don't use WiFi at all.

You have the latest 2.7.1 version of the esp8266 board package installed via the Boards Manager? If so, do you see the ESP8266WiFi.h file at C:\Users\pusername]\AppData\Local\arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\ESP8266WiFi\ESP8266WiFi.h?

What board are you selecting in the IDE? When I tried compiling with the Arduino IDE with the 2.7.1 board package and Generic ESP8266 Module selected I did not get the error you are seeing.

**Comment by bubba198** [comment]
@jburhenn Hi Jake, I actually have 2.0.x board package of ESP8266. I can't go beyond 2.0 because then most of my other libraries break (LCD drivers, etc). 

I suspected that's the issue and today I confirmed it. I wiped brand new laptop image with 2.7.1 and then it compiles just fine (but nothing else would compile from my prior work) so it is very safe to say that Cayenne_example_ESP8266_5-30-2020.ino does require board version 2.7.1

Thank you

**Comment by jburhenn** [comment]
Yeah, an out-of-date version of the board package could explain the issue. You shouldn't need the most recent 2.7.1 version for our library to work but you would need something a bit more recent than 2.0.0.

Closing this issue since it appears to be due to a board package incompatibility.
